feat: podman desktop extension
redhat-developer/podman-desktop-image-checker-openshift-ext pull request #34
Opened 2023-12-05 09:47 UTC by feloy

An image can be created and pushed with `./scripts/build.sh <image-name> <tag>`

This creates a multi-platform image for (windows,linux,darwin) x (amd64,arm64).

Fixes https://github.com/redhat-developer/podman-desktop-image-checker-openshift-ext/issues/21

2023-12-05 10:30 UTC, lstocchi commented
I built the extension, installed it on Desktop but i receive this message for every image.
![image](https://github.com/redhat-developer/podman-desktop-image-checker-openshift-ext/assets/49404737/d1666645-0521-4261-a7c3-dd27c57cf84b)

2023-12-05 10:33 UTC, lstocchi commented
Not sure if this is expected bc i have to do something or there is an error, so asking

2023-12-05 10:45 UTC, feloy commented
> Not sure if this is expected bc i have to do something or there is an error, so asking

Which OS/arch are you using?

2023-12-05 10:47 UTC, lstocchi commented
windows amd64

2023-12-05 11:14 UTC, feloy commented
Which version of Podman desktop are you using? Particularly, does it include this patch? https://github.com/containers/podman-desktop/pull/5069

2023-12-05 11:21 UTC, lstocchi commented
> Which version of Podman desktop are you using? Particularly, does it include this patch? [containers/podman-desktop#5069](https://github.com/containers/podman-desktop/pull/5069)

i was using my local main branch but probably it was not rebased, let me re-try

2023-12-05 11:27 UTC, lstocchi commented
Ok it was a problem with my branch. Works fine, thanks @feloy

2023-12-05 11:28 UTC, lstocchi approved these changes
LGTM

2023-12-05 11:28 UTC, lstocchi commented on podman-desktop-extension/package.json
> +    "@podman-desktop/api": "https://gitpkg.now.sh/containers/podman-desktop/packages/extension-api?main",
Why don't you use a version here?

2023-12-05 11:33 UTC, feloy commented on podman-desktop-extension/package.json
> +    "@podman-desktop/api": "https://gitpkg.now.sh/containers/podman-desktop/packages/extension-api?main",
I don't think the latest release (1.5.3) includes the necessary changes in the API

2023-12-05 11:45 UTC, jeffmaury commented on podman-desktop-extension/package.json
> +    "@podman-desktop/api": "https://gitpkg.now.sh/containers/podman-desktop/packages/extension-api?main",
next is the version to use

2023-12-05 11:49 UTC, jeffmaury commented on Containerfile
> +COPY --from=cli-builder /opt/app-root/src/bin/doa.cross.linux.${PLATFORM_ARG} /extension/doa.linux
Why don't we have an image per os/arch with a single binary ?

2023-12-05 16:03 UTC, jeffmaury requested changes

2023-12-05 16:03 UTC, jeffmaury commented on podman-desktop-extension/src/extension.ts
> +  const provider = extensionApi.provider.createProvider({
Should be removed, not needed

2023-12-08 14:24 UTC, feloy commented on Containerfile
> +COPY --from=cli-builder /opt/app-root/src/bin/doa.cross.linux.${PLATFORM_ARG} /extension/doa.linux
After some tests, it appears that, on Windows, the Linux image will be downloaded, not the Windows one (as the container runtime is Linux-based).

For me, the smallest granularity we can have is the platform.

2023-12-08 16:30 UTC, jeffmaury commented on podman-desktop-extension/package.json
> +  "displayName": "OpenShift Checker",
```suggestion
  "displayName": "Red Hat OpenShift Checker",
```

2023-12-18 16:29 UTC, jeffmaury reviewed
I can't test the extension: here is what I have when I run it with --extension-folder

![image](https://github.com/redhat-developer/podman-desktop-image-checker-openshift-ext/assets/695993/7e7c0749-32d4-4282-97bd-d095d6d6d4e1)

I tested against main and v1.6.3 of Podman Desktop source code

2023-12-18 17:04 UTC, feloy commented on podman-desktop-extension/package.json
> +    "@types/node": "^20.9.4",
Are you trying to run by moving the sources into the podman desktop sources and building it as the same time as PD? 

Or by downloading an image from the Extensions page?

2023-12-18 17:06 UTC, jeffmaury commented on podman-desktop-extension/package.json
> +    "@types/node": "^20.9.4",
I'm using with different code bases but from the Podman Dekstop one, I'm running `yarn watch --extension-folder ../../redhat-developer/podman-desktop-image-checker-openshift-ext/podman-desktop-extension/`

2023-12-18 17:19 UTC, feloy commented on podman-desktop-extension/package.json
> +    "@types/node": "^20.9.4",
OK, I didn't understand it was expected to be ran this way also.

I think I'll have to adapt the tsconfig.json file to make it compatible for both this way and built as an independent module into an image.

2023-12-18 18:00 UTC, feloy commented on podman-desktop-extension/package.json
> +    "@types/node": "^20.9.4",
ok, I've made a fix to make it buildable with `yarn watch` and inside an image.

But with `yarn watch`, you still won't have the `doa` executable built, and it won't be found by the extension. Do we want to automate this in some way?

2023-12-20 11:31 UTC, jeffmaury requested changes
When I try to build the image, I have a warning that yarn build but there is no lock file

Also would be good to add node_modules to .gitignore

2023-12-20 13:20 UTC, feloy commented
> When I try to build the image, I have a warning that yarn build but there is no lock file
> 
> Also would be good to add node_modules to .gitignore

It should be fixed with the latest commit

2023-12-20 13:34 UTC, jeffmaury approved these changes
LGTM

2023-12-20 14:47 UTC, merged