ci: release
redhat-developer/podman-desktop-image-checker-openshift-ext pull request #39
Opened 2023-12-21 13:07 UTC by feloy

2023-12-21 13:14 UTC, jeffmaury requested changes

2023-12-21 13:14 UTC, jeffmaury commented on .github/workflows/release.yaml
> +      - uses: actions/checkout@v3
Use v4

2023-12-21 13:40 UTC, jeffmaury approved these changes
LGTM
Not sure why we need to update podman (multi arch ?)

2023-12-21 13:45 UTC, feloy commented
> LGTM Not sure why we need to update podman (multi arch ?)

Yes, podman v3 fails to build multi-arch images

2024-01-02 09:00 UTC, lstocchi approved these changes

2024-01-31 16:39 UTC, merged