fix release script to stay in same repo
redhat-developer/podman-desktop-image-checker-openshift-ext pull request #46
Opened 2024-02-16 15:02 UTC by feloy

In the step `tag` the script is modifying the package.json file, but we are building the image from another step, where we checkout the repository agin, and the changes on the package.json file are lost

2024-02-16 15:05 UTC, benoitf approved these changes

2024-02-16 15:06 UTC, benoitf requested changes
I think you need to checkout from the tag, not change the order

2024-02-16 15:07 UTC, benoitf commented
```yaml
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
```

2024-02-19 07:49 UTC, jeffmaury approved these changes
LGTM

2024-02-19 08:20 UTC, merged