test: added image checker extension verification tests
redhat-developer/podman-desktop-image-checker-openshift-ext pull request #61
Opened 2024-12-02 13:32 UTC by rostalan

2024-12-02 15:29 UTC, odockal commented on .gitignore
> +pnpm-lock.yaml
remove pnpm-lock and tests/playwright from .gitignore. They should be considered. You can add folders like `output`.

2024-12-02 15:30 UTC, odockal commented on podman-desktop-extension/package.json
> +    "test:e2e": "cross-env npm run test:e2e:setup npx playwright test ../tests/src",
instead of `../tests` it should be `./tests` right?

2024-12-02 15:31 UTC, odockal commented on podman-desktop-extension/package.json
> +    "vitest": "^1.0.0",
I would not downgrade any package. especially not from version 5 -> 1.

2024-12-02 15:31 UTC, odockal commented on podman-desktop-extension/package.json
> +  "packageManager": "pnpm@9.14.1+sha512.7f1de9cffea40ff4594c48a94776112a0db325e81fb18a9400362ff7b7247f4fbd76c3011611c9f8ac58743c3dc526017894e07948de9b72052f874ee2edfdcd"
Switching to pnpm package manager is whole different PR.

2024-12-02 15:32 UTC, odockal commented on podman-desktop-extension/tests/src/pages/image-checker-page.ts
> +export class ImageCheckerExtensionPage extends ExtensionDetailsPage {
file name differs from class name, please align them.

2024-12-02 15:33 UTC, odockal commented on podman-desktop-extension/tests/src/pages/image-checker-image-tab-page.ts
> +export class ImageCheckerDetailsPage extends DetailsPage {
filename differs from class name.

2024-12-02 15:37 UTC, odockal commented on podman-desktop-extension/tests/src/image-checker.spec.ts
> +  test.describe.serial('Red Hat Image Checker extension installation', () => {
do we need two describes blocks?

2024-12-02 19:26 UTC, rostalan commented on podman-desktop-extension/package.json
> +    "vitest": "^1.0.0",
newest stable is actually 2.1.8

2024-12-06 08:57 UTC, jeffmaury reviewed
LGTM. But I have 2 questions:

- is the switch to module related to this PR ? I have the feeling it should be a separate PR
- when running the tests, I noticed the report reported a skipped test is this expected ?

2025-01-27 09:56 UTC, benoitf approved these changes

2025-01-27 09:57 UTC, benoitf requested changes
as Jeff mentionned, all changes to the main package.json should be done prior to just the e2e part

2025-01-27 16:02 UTC, rostalan commented
Added separate pr for the package.json: [here](https://github.com/redhat-developer/podman-desktop-image-checker-openshift-ext/pull/63)

2025-03-10 09:23 UTC, rostalan commented
rebased, ready for review @odockal @jeffmaury @benoitf

2025-03-11 07:35 UTC, jeffmaury reviewed
Not sure the dependency update in yarn.lock should be part of this PR

2025-03-18 09:45 UTC, odockal approved these changes
LGTM

2025-03-20 07:48 UTC, jeffmaury approved these changes
LGTM

2025-03-24 10:53 UTC, rostalan commented
@benoitf could you re-review as well?

2025-03-24 11:32 UTC, benoitf approved these changes
LGTM

2 nits to be fixed before merging: it seems some files are not ending with a newline

![image](https://github.com/user-attachments/assets/0e54c4a3-8f95-4303-86e5-b24e251868a6)

2025-03-24 11:32 UTC, merged